version: "3"

services:
  api:
    image: node:lts
    restart: unless-stopped
    ports:
      - 4000:4000
    volumes:
      - ./src:/home/node/app
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_NAME=example
      - DB_USERNAME=example
      - DB_PASSWORD=example
      - DEBUG=true
    user: "501:0"
    working_dir: /home/node/app
    command:
      - npm
      - run
      - dev
    depends_on:
      - db

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  pg-data:
